program testBadInput4;

#include("stdlib.hhf");

static
    input: int32;

begin testBadInput4;
    // This forever loop repeats until the user enters
    // a good integer and the break statement below
    // exits the loop.
    forever
        try
            stdout.put("Enter an integer value: ");
            stdin.get(input);
            stdout.put("The first input value was: ", input, nl);
        
        unprotected
            break;
        
          exception(ex.ValueOutOfRange);
            stdout.put("The value was too large" nl);

          exception(ex.ConversionError);
            stdout.put("Your input contained illegal characters" nl);

        endtry;

    endfor;

    // Note that the following code is outside the loop and there
    // is no try..endtry statement protecting this code.

    stdout.put("Enter another number: ");
    stdin.get(input);
    stdout.put("The new number is: ", input, nl);

end testBadInput4;